/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Cohere / Synthetica design tokens.
        // Hex values live on CSS custom properties in src/styles/index.css so
        // every color derives from the single source of truth.
        cohere: {
          primary: "var(--c-primary)",
          black: "var(--c-black)",
          ink: "var(--c-ink)",
          "deep-green": "var(--c-deep-green)",
          "dark-navy": "var(--c-dark-navy)",
          canvas: "var(--c-canvas)",
          background: "var(--c-background)",
          surface: "var(--c-surface)",
          "surface-lowest": "var(--c-surface-lowest)",
          "surface-low": "var(--c-surface-low)",
          "surface-container": "var(--c-surface-container)",
          "surface-high": "var(--c-surface-high)",
          "surface-highest": "var(--c-surface-highest)",
          "surface-variant": "var(--c-surface-variant)",
          "soft-stone": "var(--c-soft-stone)",
          "pale-green": "var(--c-pale-green)",
          "pale-blue": "var(--c-pale-blue)",
          hairline: "var(--c-hairline)",
          "border-light": "var(--c-border-light)",
          "card-border": "var(--c-card-border)",
          muted: "var(--c-muted)",
          slate: "var(--c-slate)",
          "body-muted": "var(--c-body-muted)",
          "on-surface": "var(--c-on-surface)",
          "on-surface-variant": "var(--c-on-surface-variant)",
          "on-primary": "var(--c-on-primary)",
          "on-secondary": "var(--c-on-secondary)",
          "on-secondary-container": "var(--c-on-secondary-container)",
          "secondary": "var(--c-secondary)",
          "secondary-container": "var(--c-secondary-container)",
          "action-blue": "var(--c-action-blue)",
          "focus-blue": "var(--c-focus-blue)",
          "info-blue": "var(--c-info-blue)",
          coral: "var(--c-coral)",
          "coral-soft": "var(--c-coral-soft)",
          "form-focus": "var(--c-form-focus)",
          error: "var(--c-error)",
          "error-container": "var(--c-error-container)",
          success: "var(--c-success)",
        }
      },
      fontFamily: {
        display: ["'Hanken Grotesk'", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        sans: ["'Hanken Grotesk'", "Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "72px", letterSpacing: "-0.02em" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em" }],
        "feature-title": ["24px", { lineHeight: "32px" }],
        "body-large": ["18px", { lineHeight: "28px" }],
        "body-main": ["16px", { lineHeight: "24px" }],
        caption: ["14px", { lineHeight: "20px" }],
        micro: ["12px", { lineHeight: "16px" }],
        "label-mono": ["13px", { lineHeight: "18px", letterSpacing: "0.02em" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        ai: "22px",
        xl: "30px",
        pill: "32px",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "80px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
      },
      transitionTimingFunction: {
        cohere: "cubic-bezier(0.16, 1, 0.3, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
    },
  },
  plugins: [],
}
